apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: qianxue-test-fatebook-ns

metadata:
  name: qianxue-test-fatebook
  namespace: qianxue-test-fatebook-ns

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- configmap.yaml
- env-configmap.yaml
- hpa.yaml

images:
- name: omaticaya/qianxue-test-fatebook
  newTag: 1.0.13

commonLabels:
  app: qianxue-test-fatebook
  managed-by: argocd


